### ISSUE TITLE
gantt charts - setting the font size in a mermaid json config file or a css file doesn't work

### ISSUE THREAD

**Issue by rhz** [mermaidjs/mermaid.cli#62]
Setting the font size in a mermaid json config file passed to mermaid.cli via its `-c` option doesn't change the font size in the output when generating gantt charts. The same happens when passing a css file using the `-C` option with the following content:
```css
html { font-size: 14px; }
```

It seems the css imposed by the theme (even if you chose no theme) overrides the font size given in the json config file or the css file. The only workaround that I've found is to pass the following css instead
```css
html { font: 14px/14px "Open-Sans" !important; }
```
The `!important` bit is key to make it work.
